
android_library(
    name = "audio",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:androidx_core_core",
    ],
    visibility = [
        "//src/main/java/org/lizlooney/pitchdetector:__pkg__",
    ],
)
